### ISSUE TITLE
bot help

### ISSUE THREAD

**Issue by friktiny** [MiraBellierr/Jasmine#4]
can i get help in bot plz?
showing this 
![image](https://user-images.githubusercontent.com/76273378/121838602-f4bdcd00-ccf7-11eb-9d8b-ae6bf4752c95.png)

**Comment by MiraBellierr** [comment]
Hi there, please go to [contributing](https://github.com/MiraBellierr/Jasmine/blob/main/CONTRIBUTING.md#running-the-bot-locally) to know how to run the bot locally.
